name = "spacescape-worker"
main = "index.js"
compatibility_date = "2024-03-20"

[durable_objects]
bindings = [
  { name = "GAMEROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"] 